# Generated by Django 2.2.15 on 2020-08-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkhouseAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.CharField(blank=True, db_column='snapshot-date', max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('fnsku', models.CharField(blank=True, max_length=255, null=True)),
                ('asin', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, db_column='product-name', max_length=255, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('avaliable_quantity_sellable_field', models.CharField(blank=True, db_column='avaliable-quantity(sellable)', max_length=255, null=True)),
                ('qty_with_removals_in_progress', models.CharField(blank=True, db_column='qty-with-removals-in-progress', max_length=255, null=True)),
                ('inv_age_0_to_90_days', models.CharField(blank=True, db_column='inv-age-0-to-90-days', max_length=255, null=True)),
                ('inv_age_91_to_180_days', models.CharField(blank=True, db_column='inv-age-91-to-180-days', max_length=255, null=True)),
                ('inv_age_181_to_270_days', models.CharField(blank=True, db_column='inv-age-181-to-270-days', max_length=255, null=True)),
                ('inv_age_271_to_365_days', models.CharField(blank=True, db_column='inv-age-271-to-365-days', max_length=255, null=True)),
                ('inv_age_365_plus_days', models.CharField(blank=True, db_column='inv-age-365-plus-days', max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('qty_to_be_charged_ltsf_6_mo', models.CharField(blank=True, db_column='qty-to-be-charged-ltsf-6-mo', max_length=255, null=True)),
                ('projected_ltsf_6_mo', models.CharField(blank=True, db_column='projected-ltsf-6-mo', max_length=255, null=True)),
                ('qty_to_be_charged_ltsf_12_mo', models.CharField(blank=True, db_column='qty-to-be-charged-ltsf-12-mo', max_length=255, null=True)),
                ('projected_ltsf_12_mo', models.CharField(blank=True, db_column='projected-ltsf-12-mo', max_length=255, null=True)),
                ('units_shipped_last_7_days', models.CharField(blank=True, db_column='units-shipped-last-7-days', max_length=255, null=True)),
                ('units_shipped_last_30_days', models.CharField(blank=True, db_column='units-shipped-last-30-days', max_length=255, null=True)),
                ('units_shipped_last_60_days', models.CharField(blank=True, db_column='units-shipped-last-60-days', max_length=255, null=True)),
                ('units_shipped_last_90_days', models.CharField(blank=True, db_column='units-shipped-last-90-days', max_length=255, null=True)),
                ('alert', models.CharField(blank=True, max_length=255, null=True)),
                ('your_price', models.CharField(blank=True, db_column='your-price', max_length=255, null=True)),
                ('sales_price', models.CharField(blank=True, max_length=255, null=True)),
                ('lowest_price_new', models.CharField(blank=True, max_length=255, null=True)),
                ('lowest_price_used', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_action', models.CharField(blank=True, db_column='Recommended action', max_length=255, null=True)),
                ('healthy_inventory_level', models.CharField(blank=True, db_column='Healthy Inventory Level', max_length=255, null=True)),
                ('recommended_sales_price', models.CharField(blank=True, db_column='Recommended sales price', max_length=255, null=True)),
                ('recommended_sale_duration_days_field', models.CharField(blank=True, db_column='Recommended sale duration (days)', max_length=255, null=True)),
                ('recommended_removal_quantity', models.CharField(blank=True, db_column='Recommended Removal Quantity', max_length=255, null=True)),
                ('estimated_cost_savings_of_recommended_actions', models.CharField(blank=True, db_column='estimated-cost-savings-of-recommended-actions', max_length=255, null=True)),
                ('sell_through', models.CharField(blank=True, db_column='sell-through', max_length=255, null=True)),
                ('item_volume', models.CharField(blank=True, db_column='item-volume', max_length=255, null=True)),
                ('volume_units', models.CharField(blank=True, db_column='volume-units', max_length=255, null=True)),
                ('storage_type', models.CharField(blank=True, db_column='storage-type', max_length=255, null=True)),
            ],
            options={
                'db_table': 'workhouseage',
            },
        ),
    ]
